# encoding:utf-8

require 'socket'
require 'openssl'

def main
    # Start TCP server
    server = TCPServer.new(4481)

    # Open ssl
    ctx = OpenSSL::SSL::SSLContext.new
    ctx.cert, ctx.key = create_self_signed_cert(
                  1024,
                  [['CN', 'localhost']],
                  "Generated by Ruby/OpenSSL"
              )
    ctx.verify_mode =OpenSSL::SSL::VERIFY_PEER

    # Generate ssl server
    ssl_server = OpenSSL::SSL::SSLServer.new(server, ctx)
    
    # Process link
    connection = ssl_server.accept
    connection.write("SB JCT")
    connection.close
end 
